### ISSUE TITLE
S3 metadata on upload

### ISSUE THREAD

**Issue by PsyTae** [RiptideElements/s3fs#73]
Is there a way when you are coping a file up to the AWS S3 from your computer file system to add custom s3 metadata using s3fs?  [AWS CP](http://docs.aws.amazon.com/cli/latest/reference/s3/cp.html)

aws cli 
`aws s3 cp c:\Code\xxxx.js s3://uploadbucket --metadata source=xxxxxx`

s3fs
```
var S3FS = require('s3fs');
var s3Bucket = XXXXXXXXXX;
// AMAZON Connection Info:
var s3fsImpl = new S3FS(s3Bucket, {
    accessKeyId: 'XXXXXXXXXXXXXXXXXXXX',
    secretAccessKey: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    region: 'us-east-1'
});
s3fsImpl.create();
var stream = fs.createReadStream(path); //c:\Code\xxxx.js
return s3fsImpl.writeFile(filename /*SOME S3 OPTIONS HERE MAYBE*/, stream).then(function () {
    console.log("File Saved");
}, function(reason) {
  throw reason;
});
```

**Comment by DavidTPate** [comment]
Correct, you can pass whatever options the [S3 API supports](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property). Here's a [test](https://github.com/RiptideElements/s3fs/blob/0a9aee419e29b4b1b01b3484c7eda43f358ba40d/test/file.js#L115-L123) where we pass `ContentType` which is recorded by S3 as metadata and used for serving.

**Comment by PsyTae** [comment]
return s3fsImpl.writeFile(filename, stream, {x-amz-meta-source: 'xxxxxx'}).then(function () {
                                              ^

SyntaxError: Unexpected token -
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:1003:3

**Comment by PsyTae** [comment]
return s3fsImpl.writeFile(filename, stream, {'x-amz-meta-source': 'xxxxxx'}).then(function () {

Unhandled rejection UnexpectedParameter: Unexpected key 'x-amz-meta-source' found in params
    at ParamValidator.fail (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\param_validator.js:50:37)
    at ParamValidator.validateStructure (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\param_validator.js:77:14)
    at ParamValidator.validateMember (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\param_validator.js:88:21)
    at ParamValidator.validate (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\event_listeners.js:89:42)
    at Request.callListeners (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at callNextListener (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\sequential_executor.js:95:12)
    at C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\event_listeners.js:75:9
    at finish (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\config.js:293:7)
    at C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\config.js:309:9
    at Credentials.get (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\credentials.js:126:7)
    at getAsyncCredentials (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\config.js:303:24)
    at Config.getCredentials (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\config.js:323:9)
    at Request.VALIDATE_CREDENTIALS (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\event_listeners.js:70:26)
    at Request.callListeners (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\sequential_executor.js:101:18)
    at Request.emit (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\sequential_executor.js:77:10)

**Comment by PsyTae** [comment]
```
return s3fsImpl.writeFile(filename, stream, { source: 'fleet'}).then(function () {

Unhandled rejection UnexpectedParameter: Unexpected key 'source' found in params
    at ParamValidator.fail (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\param_validator.js:50:37)
    at ParamValidator.validateStructure (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\param_validator.js:77:14)
    at ParamValidator.validateMember (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\param_validator.js:88:21)
    at ParamValidator.validate (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\event_listeners.js:89:42)
    at Request.callListeners (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at callNextListener (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\sequential_executor.js:95:12)
    at C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\event_listeners.js:75:9
    at finish (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\config.js:293:7)
    at C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\config.js:309:9
    at Credentials.get (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\credentials.js:126:7)
    at getAsyncCredentials (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\config.js:303:24)
    at Config.getCredentials (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\config.js:323:9)
    at Request.VALIDATE_CREDENTIALS (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\event_listeners.js:70:26)
    at Request.callListeners (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\sequential_executor.js:101:18)
    at Request.emit (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
```

**Comment by PsyTae** [comment]
```
return s3fsImpl.writeFile(filename, stream, { 'source': 'fleet'}).then(function () {

Unhandled rejection UnexpectedParameter: Unexpected key 'source' found in params
    at ParamValidator.fail (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\param_validator.js:50:37)
    at ParamValidator.validateStructure (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\param_validator.js:77:14)
    at ParamValidator.validateMember (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\param_validator.js:88:21)
    at ParamValidator.validate (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\event_listeners.js:89:42)
    at Request.callListeners (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at callNextListener (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\sequential_executor.js:95:12)
    at C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\event_listeners.js:75:9
    at finish (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\config.js:293:7)
    at C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\config.js:309:9
    at Credentials.get (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\credentials.js:126:7)
    at getAsyncCredentials (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\config.js:303:24)
    at Config.getCredentials (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\config.js:323:9)
    at Request.VALIDATE_CREDENTIALS (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\event_listeners.js:70:26)
    at Request.callListeners (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\sequential_executor.js:101:18)
    at Request.emit (C:\nodeCode\node_modules\s3fs\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
```

**Comment by PsyTae** [comment]
[User-Defined Metadata](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-metadata)

When uploading an object, you can also assign metadata to the object. You provide this optional information as a name-value pair when you send a PUT or POST request to create the object. When uploading objects using the REST API the optional user-defined metadata names must begin with "x-amz-meta-" to distinguish them from other HTTP headers. When you retrieve the object using the REST API, this prefix is returned. When uploading objects using the SOAP API, the prefix is not required. When you retrieve the object using the SOAP API, the prefix is removed, regardless of which API you used to upload the object.

**Comment by DavidTPate** [comment]
```js
return s3fsImpl.writeFile(filename, stream, {x-amz-meta-source: 'xxxxxx'}).then(function () {
                                              ^

SyntaxError: Unexpected token -
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:1003:3
```

The above has invalid javascript. Your options object would need to have quotes around the key due to the `-` characters. Ie. `{'x-amz-meta-source': 'xxxxxx'}`.

As for the others it's because you are attempting to use the docs from the S3 API to use with the S3 SDK. If you take a look [here](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property) you'll notice  `Metadata — (map<String>) A map of metadata to store with the object in S3.`. So you can specify within your object something like:

```js
return s3fsImpl.writeFile(filename, stream, { Metadata: { source: 'xxxxxx' }});
```

**Comment by PsyTae** [comment]
Thanks that worked!!
